apiVersion: batch/v1
kind: Job
metadata:
  name: create-env-ec2-sql-${{values.name}}
  namespace: ${{values.namespace}}
spec:
  template:
    spec:
      serviceAccountName: tf-runner
      containers:
      - name: trigger
        image: amazon/aws-cli:latest
        command:
        - /bin/bash
        - -c
        - |
          aws --region ${{values.aws_region}} codebuild start-build --project-name modernengg-codebuild-ec2-db
      restartPolicy: Never

